# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt6 UI code generator 6.0.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import requests
from PyQt6 import QtCore, QtGui, QtWidgets
import clientui

class Messenger(QtWidgets.QMainWindow, clientui.Ui_MainWindow):
    def __init__(self, server_hosts):
        super().__init__()
        self.setupUi(self)

        self.server_hosts = server_hosts
        # to run on button clock
        self.pushButton.pressed.connect(self.send_message)

        self.after = 0
        # to run by timer
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.get_messages)
        self.timer.start(1000)

    def get_messages(self):
        try:
            response = requests.get(
                f"{self.server_hosts}/messages",
                params={'after': self.after}
            )
        except:
            self.textBrowser.append('Сервер не доступен')
            return

        messages = response.json()['message']
        for message in messages:
            self.print_message(message)
            self.after = message['time']

    def print_message(self, message):
        self.textBrowser.append(message['name'] + ':' )
        self.textBrowser.append(message['text'])
        self.textBrowser.append('')


    def send_message(self):
        name = self.lineEdit.text()
        text = self.textEdit.toPlainText()
        try:
            response = requests.post(
                 f"{self.server_hosts}/send",
                 json={'name': name, 'text': text})
        except:
            self.textBrowser.append('Сервер не доступен')
            self.textBrowser.append('')
            return

        if response.status_code != 200:
            self.textBrowser.append('Произошла ошибка. Проверьте имя и текст')
            self.textBrowser.append('')
            return

        self.textEdit.setText('')


app = QtWidgets.QApplication([])
window = Messenger(server_hosts='https://46611455aa21.ngrok.io')
window.show()
app.exec()